
name: gym_management_app
description: Gym Management app
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.0
  firebase_storage: ^11.2.0
  provider: ^6.0.5
  intl: ^0.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
